Can't save recipes without name and description
rozPierog/Cofi pull request #45
Opened 2022-01-26 08:02 UTC by Sherlock-Holmes-2-2-1

# Description
Now users cant save recipes without entering the name and description, basically name and description won't be blank.

I have added a simple if-else in MainActitvity.kt. If the name and description of recipe is empty, it will show a toast requesting user to enter the same.

## Type of change

- [ ] Bug fix

2022-01-26 16:15 UTC, rozPierog requested changes
Hey, congratulations on your first Open Source PR on Github!
Sadly I'm not gonna merge it yet as I have couple of suggestions. You can see them above.

Also run ktlint before committing, it will format your code in according to style guide of the repository. You can do this by doing `./gradlew ktlintFormat` in terminal or by launching `ktlintFormat` task from `app/build.gradle` file. 
Also useful keyboard shortcut to remember is `CTRL+ALT+L` or `⌘⌥L`  (if you are on macOS) this will format current file with according to Android Studio settings.

2022-01-26 16:15 UTC, rozPierog commented on app/src/main/java/com/omelan/cofi/MainActivity.kt
> +                    }else{Toast.makeText(applicationContext,"Name and description can't be empty.",Toast.LENGTH_SHORT).show()  }
There shouldn't be any hardcoded strings. All strings should be in `values/strings.xml` and refereed in code via resource id

2022-01-26 16:15 UTC, rozPierog commented on app/src/main/java/com/omelan/cofi/MainActivity.kt
> +                    if(isRecipeSave.equals(true)  ){goBack()}
Also you could have omitted `isRecipeSave` and just move `goBack()` call to the body of an `if`

2022-01-26 16:15 UTC, rozPierog commented on app/src/main/java/com/omelan/cofi/MainActivity.kt
> +        var isRecipeSave = false
Check your code for typos before submitting 
```suggestion
        var isRecipeSaved = false
```

2022-01-27 03:32 UTC, Sherlock-Holmes-2-2-1 commented
Okay, I'll make the changes accordingly, then send the PR again.

2022-01-30 13:00 UTC, rozPierog commented
Hey @Sherlock-Holmes-2-2-1 sorry but I was already making changes to Recipe Edit page so I've added necessary changes in #49 so I'm gonna close this issue.

2022-01-30 13:00 UTC, closed without merging